# Avnatis Mapping Instructions

The following describes the process for mapping the current Avantis Classes to the new Classification system. 

## Load SPARQL data

The first step is to run SPARQL queires in protege to get the revelent metadata from the new classes. The SPARQL queires should look for classes with the specific annotation propertys:
1. is_equivalent_to_Avantis_class
2. is_equivalent_to_Avantis_category
3. is_equivalent_to_tag_code
4. is_superclass_of_Avantis_class
5. is_superclass_of_Avantis_category
6. is_superclass_of_tag_code
The following code can be modified to acomplish this task. 

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX tw: <http://www.toronto.ca/TWONTO#>

SELECT (STR(?label) as ?OWL) (STR(?object) as ?Avantis)
WHERE { 
    ?entityIRI tw:is_equivalent_to_Avantis_class ?object ;
              rdfs:label ?label .
}
```
Once the SPARQL queires are saved, they are open in python pandas dataframes. This is done with the following code:

In [45]:
import pandas as pd

df = pd.read_excel("SPARQL_class.xlsx", header= 1)
Class = dict(zip(df['Avantis_Class'],df['TWONTO']))

TWONTO_classes = pd.read_excel('TWONTO_classes.xlsx')
TWONTO_classes = TWONTO_classes['Classes'].tolist()
df

,TWONTO,Avantis_Class
0,http://www.toronto.ca/TWONTO#channel_gate,Gate
1,http://www.toronto.ca/TWONTO#blower,Blower
2,http://www.toronto.ca/TWONTO#instrument_air_or...,Air Instrument
3,http://www.toronto.ca/TWONTO#UV_disinfection_a...,Ultraviolet Disinfection
4,http://www.toronto.ca/TWONTO#clarifier,Clarifier
...,...,...
116,http://www.toronto.ca/TWONTO#filtration_tank,Biofilter
117,http://www.toronto.ca/TWONTO#load_break_discon...,Load Break Switch
118,http://www.toronto.ca/TWONTO#breaker,Switchgear
119,http://www.toronto.ca/TWONTO#cooling_tower,Cooling Tower
120,http://www.toronto.ca/TWONTO#air_silencer,Silencer

There is an additonal step were the two column are saved as a dictionary. A python dictionary is a simple key value pair.

In [46]:
df = pd.read_excel("SPARQL_superclass.xlsx", header= 1)
Super_Class = dict(zip(df['Super_Class'],df['TWONTO']))

df = pd.read_excel("SPARQL_tag.xlsx", header= 1)
Tag = dict(zip(df['Tag'],df['TWONTO']))

df = pd.read_excel("SPARQL_supertag.xlsx", header= 1)
Super_Tag = dict(zip(df['Super_Tag'],df['TWONTO']))

df = pd.read_excel("SPARQL_category.xlsx", header= 1)
Category = dict(zip(df['Category'],df['TWONTO']))

df = pd.read_excel("SPARQL_supercategory.xlsx", header= 1)
Super_Category = dict(zip(df['Super_Category'],df['TWONTO']))

df = pd.read_excel("manualMatch.xlsx", sheet_name = 'LLM capability Test Dataset')
Manual_Match = dict(zip(df['Entity_number'],df['Valid_Class']))

Tag

{'AE': 'http://www.toronto.ca/TWONTO#instrument_sensor_element',
 'CHL': 'http://www.toronto.ca/TWONTO#chlorinator_system',
 'OZ': 'http://www.toronto.ca/TWONTO#ozone_generator',
 'GB': 'http://www.toronto.ca/TWONTO#gearbox',
 'PIT': 'http://www.toronto.ca/TWONTO#pressure_transmitter',
 'LSHH': 'http://www.toronto.ca/TWONTO#level_switch',
 'CLR': 'http://www.toronto.ca/TWONTO#clarifier',
 'LSLL': 'http://www.toronto.ca/TWONTO#level_switch',
 'FM': 'http://www.toronto.ca/TWONTO#pressurized_sewer_segment',
 'WRT': 'http://www.toronto.ca/TWONTO#weight_scale',
 'G': 'http://www.toronto.ca/TWONTO#channel_gate',
 'PSH': 'http://www.toronto.ca/TWONTO#pressure_switch',
 'LSL': 'http://www.toronto.ca/TWONTO#level_switch',
 'LI': 'http://www.toronto.ca/TWONTO#instrument_gauge_or_display',
 'PSL': 'http://www.toronto.ca/TWONTO#pressure_switch',
 'SCAM': 'http://www.toronto.ca/TWONTO#security_camera',
 'LSH': 'http://www.toronto.ca/TWONTO#level_switch',
 'EV': 'http://www.toronto.ca/TWONTO#AC_evaporator_unit',
 'D': 'http://www.toronto.ca/TWONTO#dehumidifier',
 'TIT': 'http://www.toronto.ca/TWONTO#temperature_transmitter',
 'ENG': 'http://www.toronto.ca/TWONTO#engine',
 'WIT': 'http://www.toronto.ca/TWONTO#weight_scale',
 'ZT': 'http://www.toronto.ca/TWONTO#position_sensing',
 'PIP': 'http://www.toronto.ca/TWONTO#pipe_segment',
 'CI': 'http://www.toronto.ca/TWONTO#chiller',
 'CF': 'http://www.toronto.ca/TWONTO#centrifuge',
 'AHU': 'http://www.toronto.ca/TWONTO#air_handler_unit',
 'SP': 'http://www.toronto.ca/TWONTO#auto_sampler',
 'MS': 'http://www.toronto.ca/TWONTO#motion_sensor_element',
 'DEF': 'http://www.toronto.ca/TWONTO#automatic_external_defibrillator',
 'OIT': 'http://www.toronto.ca/TWONTO#operator_interface_terminal',
 'PCV': 'http://www.toronto.ca/TWONTO#valve',
 'ELV': 'http://www.toronto.ca/TWONTO#elevator',
 'LS': 'http://www.toronto.ca/TWONTO#level_switch',
 'PWU': 'http://www.toronto.ca/TWONTO#power_washer',
 'DD': 'http://www.toronto.ca/TWONTO#display_panel',
 'LT': 'http://www.toronto.ca/TWONTO#level_transmitter',
 'DR': 'http://www.toronto.ca/TWONTO#controlled_door_access',
 'UV': 'http://www.toronto.ca/TWONTO#UV_disinfection_assembly',
 'GA': 'http://www.toronto.ca/TWONTO#instrument_gauge_or_display',
 'TR': 'http://www.toronto.ca/TWONTO#transformer',
 'FE': 'http://www.toronto.ca/TWONTO#flow_element',
 'CBL': 'http://www.toronto.ca/TWONTO#cable_segment',
 'AM': 'http://www.toronto.ca/TWONTO#fixed_gas_detector',
 'DIT': 'http://www.toronto.ca/TWONTO#slude_density_meter',
 'STR': 'http://www.toronto.ca/TWONTO#strainer',
 'SB': 'http://www.toronto.ca/TWONTO#air_scrubber',
 'GDR': 'http://www.toronto.ca/TWONTO#grinder_or_comminutor',
 'LIT': 'http://www.toronto.ca/TWONTO#level_transmitter',
 'AC': 'http://www.toronto.ca/TWONTO#air_condition',
 'PI': 'http://www.toronto.ca/TWONTO#instrument_gauge_or_display',
 'HE': 'http://www.toronto.ca/TWONTO#heat_exchanger',
 'CPU': 'http://www.toronto.ca/TWONTO#computer',
 'CU': 'http://www.toronto.ca/TWONTO#AC_condenser_unit',
 'BUS': 'http://www.toronto.ca/TWONTO#5kV_electrical_cabinet',
 'AIT': 'http://www.toronto.ca/TWONTO#instrument_transmitter',
 'INJ': 'http://www.toronto.ca/TWONTO#ejector',
 'DT': 'http://www.toronto.ca/TWONTO#condensate_trap',
 'CL': 'http://www.toronto.ca/TWONTO#classifier',
 'FX': 'http://www.toronto.ca/TWONTO#flame_arrestor',
 'LP': 'http://www.toronto.ca/TWONTO#LV_electrical_panel',
 'OTF': 'http://www.toronto.ca/TWONTO#outfall_or_discharge_point',
 'DU': 'http://www.toronto.ca/TWONTO#air_duct_segment',
 'TI': 'http://www.toronto.ca/TWONTO#instrument_gauge_or_display',
 'HYD': 'http://www.toronto.ca/TWONTO#hydrant',
 'DCU': 'http://www.toronto.ca/TWONTO#dust_collector',
 'SC': 'http://www.toronto.ca/TWONTO#screen',
 'ZRT': 'http://www.toronto.ca/TWONTO#position_sensing',
 'TSH': 'http://www.toronto.ca/TWONTO#temperature_switch',
 'LRT': 'http://www.toronto.ca/TWONTO#level_transmitter',
 'BAT': 'http://www.toronto.ca/TWONTO#battery',
 'MX': 'http://www.toronto.ca/TWONTO#mixer_or_agitator',
 'UPS': 'http://www.toronto.ca/TWONTO#UPS',
 'RPU': 'http://www.toronto.ca/TWONTO#RPU_panel',
 'FU': 'http://www.toronto.ca/TWONTO#furnace',
 'RES': 'http://www.toronto.ca/TWONTO#reservoir_tank',
 'VAV': 'http://www.toronto.ca/TWONTO#variable_air_volume_unit',
 'BU': 'http://www.toronto.ca/TWONTO#burner_component_of_asset',
 'FS': 'http://www.toronto.ca/TWONTO#flow_switch',
 'FT': 'http://www.toronto.ca/TWONTO#flow_transmitter',
 'FN': 'http://www.toronto.ca/TWONTO#blower',
 'FQ': 'http://www.toronto.ca/TWONTO#flowmeter',
 'CM': 'http://www.toronto.ca/TWONTO#collector_mechanism',
 'TSL': 'http://www.toronto.ca/TWONTO#temperature_switch',
 'BL': 'http://www.toronto.ca/TWONTO#blower',
 'CT': 'http://www.toronto.ca/TWONTO#controller',
 'HTR': 'http://www.toronto.ca/TWONTO#fuel_burning_heater',
 'SCBA': 'http://www.toronto.ca/TWONTO#SCBA',
 'DP': 'http://www.toronto.ca/TWONTO#material_distribution_panel',
 'FIT': 'http://www.toronto.ca/TWONTO#flowmeter',
 'SERV': 'http://www.toronto.ca/TWONTO#server_appliance',
 'm': 'http://www.toronto.ca/TWONTO#motor',
 'ZIT': 'http://www.toronto.ca/TWONTO#position_sensing',
 'QUEN': 'http://www.toronto.ca/TWONTO#quencher',
 'AFR': 'http://www.toronto.ca/TWONTO#protection_relay',
 'CP': 'http://www.toronto.ca/TWONTO#process_control_panel',
 'TS': 'http://www.toronto.ca/TWONTO#transfer_switch',
 'RX': 'http://www.toronto.ca/TWONTO#reactor',
 'TPD': 'http://www.toronto.ca/TWONTO#trap_priming_device',
 'LAG': 'http://www.toronto.ca/TWONTO#ash_lagoon',
 'T': 'http://www.toronto.ca/TWONTO#storage_tank',
 'TT': 'http://www.toronto.ca/TWONTO#temperature_transmitter',
 'WR': 'http://www.toronto.ca/TWONTO#welding_receptacle',
 'VIT': 'http://www.toronto.ca/TWONTO#vibration_analyzer',
 'C': 'http://www.toronto.ca/TWONTO#compressor',
 'DM': 'http://www.toronto.ca/TWONTO#air_damper',
 'PT': 'http://www.toronto.ca/TWONTO#pressure_transmitter',
 'PSLL': 'http://www.toronto.ca/TWONTO#pressure_switch',
 'V': 'http://www.toronto.ca/TWONTO#valve',
 'PSHH': 'http://www.toronto.ca/TWONTO#pressure_switch',
 'BO': 'http://www.toronto.ca/TWONTO#boiler',
 'GEN': 'http://www.toronto.ca/TWONTO#generator',
 'CV': 'http://www.toronto.ca/TWONTO#conveyor',
 'CH': 'http://www.toronto.ca/TWONTO#equipment_or_access_chamber',
 'HPU': 'http://www.toronto.ca/TWONTO#hydraulic_power_pack',
 'SM': 'http://www.toronto.ca/TWONTO#large_stationary_tool',
 'MON': 'http://www.toronto.ca/TWONTO#display_panel',
 'VSS': 'http://www.toronto.ca/TWONTO#surge_suppressor',
 'ZSL': 'http://www.toronto.ca/TWONTO#position_switch',
 'BFP': 'http://www.toronto.ca/TWONTO#backflow_preventer',
 'FA': 'http://www.toronto.ca/TWONTO#annunciator_panel',
 'M': 'http://www.toronto.ca/TWONTO#motor',
 'SEN': 'http://www.toronto.ca/TWONTO#instrument_sensor_element',
 'ZSH': 'http://www.toronto.ca/TWONTO#position_switch',
 'LDR': 'http://www.toronto.ca/TWONTO#ladder',
 'RC': 'http://www.toronto.ca/TWONTO#data_logger',
 'GRF': 'http://www.toronto.ca/TWONTO#ground_and_test_device',
 'HU': 'http://www.toronto.ca/TWONTO#humidifier',
 'FCV': 'http://www.toronto.ca/TWONTO#valve',
 'WSC': 'http://www.toronto.ca/TWONTO#weight_scale',
 'SL': 'http://www.toronto.ca/TWONTO#air_silencer'}

## SQL connection
The next step connects to the Avantis SQL server to get the list of entities

In [47]:
import pyodbc
import os
from sqlalchemy.engine import URL
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

sns.set_theme()

connect = 'DSN=Avantis6-P;UID='+ os.environ['Avantis_User'] + ';PWD=' + os.environ['Avantis_Pass']
connection_url = URL.create("mssql+pyodbc", query={"odbc_connect": connect})

engine = create_engine(connection_url)

SQL1 = """SELECT Distinct MAINTENT.id as [Entity_number],
[MAINTENT].[aenm] as [Description],
MAINTENT2.id as [Parent],
MAINTENT2.aenm as [Parent_Description],
[contname] as [Category],
[entclsid] as [Class],
SUSPEND.suspoi as [Suspended]

FROM  [AvantisP].[mc].[MAINTENT]
	  Left Join [AvantisP].[mc].[ENTCLASS] on MAINTENT.entclsref_oi = ENTCLASS.entcloi
	  Left Join [AvantisP].[mc].CATVAL ON MAINTENT.cat1_oi = CATVAL.cvoi
	  Left Join MC.SUSPEND ON MAINTENT.susp_oi = SUSPEND.suspoi
	  Left Join MC.MELINK ON MAINTENT.mtnoi = MELINK.mtnchild_oi
	  Left Join MC.MAINTENT MAINTENT2 ON MELINK.mtnparn_oi = MAINTENT2.mtnoi"""


df1 = pd.read_sql(SQL1,engine)
df1 = df1[df1['Entity_number'].values != None]
df1['Tag'] = df1['Entity_number'].str.extract(r"-([a-zA-Z]+)-\d+")
df1

,Entity_number,Description,Parent,Parent_Description,Category,Class,Suspended,Tag
0,\tFCL_ELS_CBL_001D,"Electrical Power Line,4.16KV,From BUS-00B1-A t...",FCL_ELS_4.16KV_LINES,"Electrical Power Line,4.16KV",Air Handling Unit,Electrical Power Line,NaN,NaN
1,\tFCL_ELS_CBL_001F,"Electrical Power Line,4.16KV,From BUS-00B1 to ...",FCL_ELS_4.16KV_LINES,"Electrical Power Line,4.16KV",Air Handling Unit,Electrical Power Line,NaN,NaN
2,\tFCL_ELS_CBL_001G,"Electrical Power Line,4.16KV,From BUS-00B1 to ...",FCL_ELS_4.16KV_LINES,"Electrical Power Line,4.16KV",Air Handling Unit,Electrical Power Line,NaN,NaN
3,\tFCL_ELS_CBL_001H,"Electrical Power Line,4.16KV,From BUS-00B1 to ...",FCL_ELS_4.16KV_LINES,"Electrical Power Line,4.16KV",Air Handling Unit,Electrical Power Line,NaN,NaN
4,\tFCL_ELS_CBL_003F,"Electrical Power Line,4.16KV,From BUS-00B2 to ...",FCL_ELS_4.16KV_LINES,"Electrical Power Line,4.16KV",Air Handling Unit,Electrical Power Line,NaN,NaN
...,...,...,...,...,...,...,...,...
148236,YX2413A,"Pump, Dewatering, Old PS House #3",TAB-PRM-P-SUMP,"P Bldg & Old PS Buildings, Primary Treatment S...","Pump,Non Positive Displacement",Pump,NaN,NaN
148237,ZDATA PILOT,ZCity of Toronto,None,None,None,None,39026.0,NaN
148238,ZXDP ENTITY COL,DO NOT USE - City of Toronto,None,None,None,None,NaN,NaN
148239,ZXDP OTHER COL,DO NOT USE - DP Other Entities,None,None,None,None,NaN,NaN
148240,ZXDP WTR CH LOCN ORO,DO NOT USE - Toronto Water Chamber,MAIN-001,Main 001,Air Handling Unit,Chamber,NaN,NaN

In [48]:
#df1 = df1[df1['Suspended'].isna()]

In [49]:
entityMatch = pd.DataFrame()
entityMatch['Entity_number'] = df1['Entity_number'] 
entityMatch['Class_Match'] = [Class.get(x,"") for x in df1['Class']]
entityMatch['Super_Class_Match'] = [Super_Class.get(x,"") for x in df1['Class']]
entityMatch['Tag_Match'] = [Tag.get(x,"") for x in df1['Tag']]
entityMatch['Super_Tag_Match'] = [Super_Tag.get(x,"") for x in df1['Tag']]
entityMatch['Category_Match'] = [Category.get(x,"") for x in df1['Category']]
entityMatch['Super_Category_Match'] = [Super_Category.get(x,"") for x in df1['Category']]
entityMatch

,Entity_number,Class_Match,Super_Class_Match,Tag_Match,Super_Tag_Match,Category_Match,Super_Category_Match
0,\tFCL_ELS_CBL_001D,,,,,,http://www.toronto.ca/TWONTO#air_handler_unit
1,\tFCL_ELS_CBL_001F,,,,,,http://www.toronto.ca/TWONTO#air_handler_unit
2,\tFCL_ELS_CBL_001G,,,,,,http://www.toronto.ca/TWONTO#air_handler_unit
3,\tFCL_ELS_CBL_001H,,,,,,http://www.toronto.ca/TWONTO#air_handler_unit
4,\tFCL_ELS_CBL_003F,,,,,,http://www.toronto.ca/TWONTO#air_handler_unit
...,...,...,...,...,...,...,...
148236,YX2413A,http://www.toronto.ca/TWONTO#pump,,,,,
148237,ZDATA PILOT,,,,,,
148238,ZXDP ENTITY COL,,,,,,
148239,ZXDP OTHER COL,,,,,,
148240,ZXDP WTR CH LOCN ORO,http://www.toronto.ca/TWONTO#equipment_or_acce...,,,,,http://www.toronto.ca/TWONTO#air_handler_unit

In [50]:
entityMatch = pd.DataFrame()
entityMatch['Entity_number'] = df1['Entity_number']

# Step 1: Class Match
entityMatch['First_Match'] = df1['Class'].map(Class).fillna("")
class_match_count = entityMatch['First_Match'].str.len().gt(0).sum()
print(f"Class Match: {class_match_count}/{len(df1)} ({class_match_count/len(df1)*100:.2f}%)")

# Step 2: Super Class Match (if no Class Match)
entityMatch['First_Match'] = entityMatch['First_Match'].mask(entityMatch['First_Match'] == "", df1['Class'].map(Super_Class).fillna(""))
super_class_match_count = entityMatch['First_Match'].str.len().gt(0).sum() - class_match_count
print(f"Super Class Match: {super_class_match_count}/{len(df1)} ({super_class_match_count/len(df1)*100:.2f}%)")

# Step 3: Tag Match (if no Class or Super Class Match)
entityMatch['First_Match'] = entityMatch['First_Match'].mask(entityMatch['First_Match'] == "", df1['Tag'].map(Tag).fillna(""))
tag_match_count = entityMatch['First_Match'].str.len().gt(0).sum() - (class_match_count + super_class_match_count)
print(f"Tag Match: {tag_match_count}/{len(df1)} ({tag_match_count/len(df1)*100:.2f}%)")

# Step 4: Super Tag Match (if no Class, Super Class, or Tag Match)
entityMatch['First_Match'] = entityMatch['First_Match'].mask(entityMatch['First_Match'] == "", df1['Tag'].map(Super_Tag).fillna(""))
super_tag_match_count = entityMatch['First_Match'].str.len().gt(0).sum() - (class_match_count + super_class_match_count + tag_match_count)
print(f"Super Tag Match: {super_tag_match_count}/{len(df1)} ({super_tag_match_count/len(df1)*100:.2f}%)")

# Step 5: Category Match (if no match yet)
entityMatch['First_Match'] = entityMatch['First_Match'].mask(entityMatch['First_Match'] == "", df1['Category'].map(Category).fillna(""))
category_match_count = entityMatch['First_Match'].str.len().gt(0).sum() - (class_match_count + super_class_match_count + tag_match_count + super_tag_match_count)
print(f"Category Match: {category_match_count}/{len(df1)} ({category_match_count/len(df1)*100:.2f}%)")

# Step 6: Super Category Match (final fallback)
entityMatch['First_Match'] = entityMatch['First_Match'].mask(entityMatch['First_Match'] == "", df1['Category'].map(Super_Category).fillna(""))
super_category_match_count = entityMatch['First_Match'].str.len().gt(0).sum() - (class_match_count + super_class_match_count + tag_match_count + super_tag_match_count + category_match_count)
print(f"Super Category Match: {super_category_match_count}/{len(df1)} ({super_category_match_count/len(df1)*100:.2f}%)")

# Total matches
total_match_count = entityMatch['First_Match'].str.len().gt(0).sum()
print(f"Auto Matches: {total_match_count}/{len(df1)} ({total_match_count/len(df1)*100:.2f}%)")

# Step 7: Manual Match
entityMatch['First_Match'] = df1['Entity_number'].map(Manual_Match).fillna(entityMatch['First_Match'])
manual_match_count = df1['Entity_number'].map(Manual_Match).str.len().gt(0).sum()
print(f"\nManual Match: {manual_match_count}/{len(df1)} ({manual_match_count/len(df1)*100:.2f}%)")
total_match_count = entityMatch['First_Match'].str.len().gt(0).sum()
print(f"\nTotal Matches: {total_match_count}/{len(df1)} ({total_match_count/len(df1)*100:.2f}%)")

Class Match: 130705/148241 (88.17%)
Super Class Match: 1676/148241 (1.13%)
Tag Match: 8186/148241 (5.52%)
Super Tag Match: 1631/148241 (1.10%)
Category Match: 254/148241 (0.17%)
Super Category Match: 295/148241 (0.20%)
Auto Matches: 142747/148241 (96.29%)

Manual Match: 32803/148241 (22.13%)

Total Matches: 148133/148241 (99.93%)

In [51]:
#excel_class = ["Control Panel,MCC"]

#with pd.ExcelWriter('missing.xlsx', engine='openpyxl', mode='w') as writer:
#   for Value in excel_class:  
#      df1[df1['Class'] == Value].to_excel(writer, sheet_name = Value.replace(" ", "_"))
#   
#   df1[df1['Class'].isna()].to_excel(writer, sheet_name = "None")

In [52]:
df1[df1['Entity_number'].isin(entityMatch[entityMatch['First_Match'] == '']['Entity_number'])]['Tag'].unique()

array([nan, 'FIR', 'AICR', 'ANL', 'SQ', 'PDSL', 'TSHH', 'METR', 'EYE',
       'FQIR'], dtype=object)

In [53]:
df1[df1['Entity_number'].isin(entityMatch[entityMatch['First_Match'] == '']['Entity_number'])]

,Entity_number,Description,Parent,Parent_Description,Category,Class,Suspended,Tag
6,\tFCL_ELS_CBL_00L1,"Electrical Power Line,From SW-00L1 to BUS-00L1...",FCL_ELS_27.6KV_LINES,"Electrical Power Line,27.6KV",Electrical Power Line,Electrical Power Line,NaN,NaN
7,\tFCL_ELS_CBL_00L2,"Electrical Power Line,From SW-00L2 to BUS-00L2...",FCL_ELS_27.6KV_LINES,"Electrical Power Line,27.6KV",Electrical Power Line,Electrical Power Line,NaN,NaN
10,\tFCL_ELS_CBL_02CL,"Electrical Power Line,4.16KV,From BUS-00B2-A t...",FCL_ELS_4.16KV_LINES,"Electrical Power Line,4.16KV",Electrical Power Line,Electrical Power Line,NaN,NaN
7826,COM-44550,"Switch,COM-2400",TAB-ITS-WA3,Dewater Building Communications Equipment,None,Network Switch,NaN,NaN
9666,FCL-AM-FIR-0101,"Indicator, Flow, Recording,Skid 1 Process Vari...",FCL-AM-CP-0101,"Control Panel, Electrical, Pump 0101, Aqua Amm...",Meter,Meter,NaN,FIR
...,...,...,...,...,...,...,...,...
142234,WTR-161-METR-0901,Meter,CH 161 09,Chamber,Meter,Meter,NaN,METR
142235,WTR-161-METR-1401A,Meter,CH 161 14A,Chamber,Meter,Meter,NaN,METR
143188,WTR-349-METR-1001,Meter,CH 349 10,Chamber,Meter,Meter,NaN,METR
143189,WTR-349-METR-1002,Meter,CH 349 10,Chamber,Meter,Meter,NaN,METR
147810,WTR-RWL-METR-0001,"Meter, Electrical, Control Room",WTR-RWL-ELS,Electrical System,Meter,Meter,NaN,METR

In [54]:
print(len(entityMatch['First_Match'][~entityMatch['First_Match'].isin(TWONTO_classes)].unique()))
entityMatch['First_Match'][~entityMatch['First_Match'].isin(TWONTO_classes)].unique()

17

array(['', 'x', '?', 'chain_sling', 'humidity analyzer/hygrometer',
       'cart', 'route', 'http://www.toronto.ca/TWONTO#torque_switch',
       'synthetic_web_sling', 'uv_air_filter', 'sandblaster',
       'wire-rope_sling', 'bulk_head', 'rectifier',
       'ground_fault_circuit_interrupter', 'windsock',
       'http://www.toronto.ca/TWONTO#RTU_panel'], dtype=object)